### ISSUE TITLE
Error adding AC unit

### ISSUE THREAD

**Issue by jamincollins** [mill1000/midea-ac-py#106]
My device _was_ working properly with the older version from `mac-zhou/midea-ac-py`.  

However Home Assistant recently started reporting that it was unavailable.

In looking for an update and checking issues, I found your fork.

My device is seen by `msmart-ng discover`

```
$ msmart-ng discover
INFO:msmart.cli:Discovering all devices on local network.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.appsmb.com (China: False).
INFO:msmart.lan:Creating new connection to REDACTED:6444.
INFO:msmart.lan:Authenticating with REDACTED:6444.
INFO:msmart.lan:Authenticating with REDACTED:6444.
INFO:msmart.lan:Authentication successful. Expiration: 2024-03-23T10:36:46, Local key: REDACTED
INFO:msmart.cli:Found 1 devices.
INFO:msmart.cli:Found device:
{'ip': REDACTED, 'port': 6444, 'id': 151732604709890, 'online': True, 'supported': True, 'type': <DeviceType.AIR_CONDITIONER: 172>, 'name': 'net_ac_866A', 'sn': '000000P0000000Q1B07839B7866A0000', 'key': REDACTED, 'token': REDACTED}
```

I've removed the device and tried to manually re-add it with the output from the above.

It adds a device with two entities: indoor and outdoor temperature, but both report 32F which isn't correct in either case.

In the Home Assistant systemd log I see the following:

```
Mar 22 16:29:12 home-assistant hass[3530]: [msmart.device.AC.command] Unknown capability. ID: 0x0215, Size: 1.
Mar 22 16:29:12 home-assistant hass[3530]: 2024-03-22 16:29:12.208 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.midea_ac.climate.MideaClimateACDevice'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|PRESET_MODE|SWING_MODE: 57>, please create a bug report at https://github.com/mac-zhou/midea-ac-py/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Mar 22 16:29:12 home-assistant hass[3530]: 2024-03-22 16:29:12.208 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.midea_ac.climate.MideaClimateACDevice'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/mac-zhou/midea-ac-py/issues
Mar 22 16:29:12 home-assistant hass[3530]: 2024-03-22 16:29:12.208 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.midea_ac.climate.MideaClimateACDevice'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/mac-zhou/midea-ac-py/issues
Mar 22 16:29:12 home-assistant hass[3530]: 2024-03-22 16:29:12.208 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform midea_ac
Mar 22 16:29:12 home-assistant hass[3530]: Traceback (most recent call last):
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
Mar 22 16:29:12 home-assistant hass[3530]:     await asyncio.gather(*tasks)
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 589, in _async_add_entity
Mar 22 16:29:12 home-assistant hass[3530]:     entity.add_to_platform_start(
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/components/climate/__init__.py", line 393, in add_to_platform_start
Mar 22 16:29:12 home-assistant hass[3530]:     _report_turn_on_off(", ".join(_modes or []), "turn_on/turn_off")
Mar 22 16:29:12 home-assistant hass[3530]:                         ^^^^^^^^^^^^^^^^^^^^^^^
Mar 22 16:29:12 home-assistant hass[3530]: TypeError: sequence item 0: expected str instance, operational_mode_enum found
Mar 22 16:29:12 home-assistant hass[3530]: 2024-03-22 16:29:12.210 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Mar 22 16:29:12 home-assistant hass[3530]: Traceback (most recent call last):
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
Mar 22 16:29:12 home-assistant hass[3530]:     await asyncio.gather(*pending)
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
Mar 22 16:29:12 home-assistant hass[3530]:     await asyncio.gather(*tasks)
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity_platform.py", line 589, in _async_add_entity
Mar 22 16:29:12 home-assistant hass[3530]:     entity.add_to_platform_start(
Mar 22 16:29:12 home-assistant hass[3530]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/components/climate/__init__.py", line 393, in add_to_platform_start
Mar 22 16:29:12 home-assistant hass[3530]:     _report_turn_on_off(", ".join(_modes or []), "turn_on/turn_off")
Mar 22 16:29:12 home-assistant hass[3530]:                         ^^^^^^^^^^^^^^^^^^^^^^^
Mar 22 16:29:12 home-assistant hass[3530]: TypeError: sequence item 0: expected str instance, operational_mode_enum found
```

**Comment by mill1000** [comment]
Hi. Are you sure you're running an up to date version? The errors & warnings look like something is out of date.

Did you install manually or via HACS?

**Comment by jamincollins** [comment]
Installed manually, will double check tomorrow.

**Comment by jamincollins** [comment]
Looks like it was a mater of the branch changing from`master` to `main` that was making `git` say the pull was up to date when it wasn't.  Sorted it out and things appear to be working better now.

**Comment by mill1000** [comment]
Cool. Glad it's working for you! Let me know if you have any other problems.
