### ISSUE TITLE
no response from device

### ISSUE THREAD

**Issue by marnem** [mill1000/midea-ac-py#188]
Hi, from this morning noone of my midea device are visible.
I've try to reboot but the same problem.
here the log:

2024-07-19 16:50:55.411 ERROR (MainThread) [msmart.device.AC.device] Failed to query device capabilities.
2024-07-19 16:50:58.822 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.126:6444: No response from host.
2024-07-19 16:50:58.822 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.126:6444 in 6.000000 seconds. 
2024-07-19 16:50:58.893 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.125:6444: No response from host.
2024-07-19 16:50:58.893 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.125:6444 in 6.000000 seconds. 
2024-07-19 16:50:59.088 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.129:6444: No response from host.
2024-07-19 16:50:59.089 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.129:6444 in 6.010000 seconds. 
2024-07-19 16:50:59.143 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.128:6444: No response from host.
2024-07-19 16:50:59.143 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.128:6444 in 6.000000 seconds. 
2024-07-19 16:51:02.971 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.130:6444: No response from host.
2024-07-19 16:51:02.972 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.130:6444 in 6.000000 seconds. 
2024-07-19 16:51:04.783 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.127:6444: No response from host.
2024-07-19 16:51:04.783 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.127:6444 in 6.000000 seconds. 
2024-07-19 16:51:20.800 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.126:6444: No response from host.
2024-07-19 16:51:20.801 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.126:6444 in 6.000000 seconds. 
2024-07-19 16:51:20.877 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.125:6444: No response from host.
2024-07-19 16:51:20.877 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.125:6444 in 6.000000 seconds. 
2024-07-19 16:51:21.089 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.129:6444: No response from host.
2024-07-19 16:51:21.089 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.129:6444 in 6.010000 seconds. 
2024-07-19 16:51:21.139 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.128:6444: No response from host.
2024-07-19 16:51:21.139 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.128:6444 in 6.000000 seconds. 
2024-07-19 16:51:24.897 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.130:6444: No response from host.
2024-07-19 16:51:24.897 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.130:6444 in 6.000000 seconds. 
2024-07-19 16:51:26.782 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.127:6444: No response from host.
2024-07-19 16:51:26.783 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.127:6444 in 6.010000 seconds. 
2024-07-19 16:51:32.921 ERROR (MainThread) [msmart.device.AC.device] Payload '1eacb200000000080d0101048102a8c0ff000001' failed CRC and checksum. Received: 0x1, Expected: 0xA7 or 0x7F.
2024-07-19 16:51:36.023 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.128:6444: No response from host.
2024-07-19 16:51:36.024 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.128:6444 in 6.010000 seconds. 
2024-07-19 16:51:36.024 ERROR (MainThread) [msmart.device.AC.device] Failed to query device capabilities.
2024-07-19 16:51:36.503 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.126:6444: No response from host.
2024-07-19 16:51:36.503 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.126:6444 in 6.000000 seconds. 
2024-07-19 16:51:36.717 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.125:6444: No response from host.
2024-07-19 16:51:36.717 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.125:6444 in 6.000000 seconds. 
2024-07-19 16:51:43.327 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.130:6444: No response from host.
2024-07-19 16:51:43.327 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.130:6444 in 6.000000 seconds. 
2024-07-19 16:51:43.327 ERROR (MainThread) [msmart.device.AC.device] Failed to query device capabilities.
2024-07-19 16:51:43.573 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.128:6444: No response from host.
2024-07-19 16:51:43.573 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.128:6444 in 6.010000 seconds. 
2024-07-19 16:51:48.781 WARNING (MainThread) [msmart.base_device] Network timeout 192.168.2.127:6444: No response from host.
2024-07-19 16:51:48.781 WARNING (MainThread) [msmart.base_device] No response from 192.168.2.127:6444 in 6.000000 seconds. 
2024-07-19 16:51:48.812 ERROR (MainThread) [custom_components.midea_ac.coordinator] Unexpected error fetching midea_ac data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac/coordinator.py", line 39, in _async_update_data
    await self._device.refresh()
  File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 388, in refresh
    for response in await self._send_command_get_responses(cmd):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/device/AC/device.py", line 278, in _send_command_get_responses
    responses = await super()._send_command(command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/base_device.py", line 38, in _send_command
    responses = await self._lan.send(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/msmart/lan.py", line 605, in send
    self._protocol.peer, packet.hex())
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'peer'

ping to devices is ok.
the original app working ok.

**Comment by mill1000** [comment]
Did the devices change their IPs? That would be my first guess.

You could run `msmart-ng discover` on another host and compare the addresses.

**Comment by marnem** [comment]
hi,
no change of ip address...i've tried to delete one and reconnect it to homeassistant.
i see the device, but same error.

**Comment by mill1000** [comment]
In that case please provide full logs with debugging enabled.

**Comment by marnem** [comment]
[home-assistant_midea_ac_2024-07-19T14-54-07.286Z.log](https://github.com/user-attachments/files/16314364/home-assistant_midea_ac_2024-07-19T14-54-07.286Z.log)
 
here the logs with debug

**Comment by mill1000** [comment]
Did you recently upgrade to 2024.7.5 or above?

It looks like your devices are ignoring the humidity requests which causes the connection to time out.

**Comment by marnem** [comment]
hi,
after the problem i've upgrade to new version 2024.7.6, but until this morninf i've got the 2024.7.5

**Comment by marnem** [comment]
[home-assistant_midea_ac_2024-07-19T16-26-10.194Z.log](https://github.com/user-attachments/files/16314568/home-assistant_midea_ac_2024-07-19T16-26-10.194Z.log)
i've make a downgrade to version 2024.7.4, but same problem. here the new log

**Comment by mill1000** [comment]
Yeah but the underlying library didn't downgrade
```
2024-07-19 18:24:53.361 INFO (MainThread) [custom_components.midea_ac] Starting midea-ac-py. Using msmart-ng version 2024.7.2.
```

You might need to manually downgrade the library with `pip install msmart-ng==2024.5.4`, or completely removing the integration, rebooting, and then reinstalling 2024.7.4 might do it.

Or you can wait, I'm working on a fix to not enable humidity requests by default.

**Comment by marnem** [comment]
ok, i will wait the new fix...
thanks!

**Comment by mill1000** [comment]
Could you do me a favor?

Re-install the latest version, disable all but 1 device, and re-collect the logs with debugging?

**Comment by marnem** [comment]
done, here the log

[home-assistant_midea_ac_2024-07-19T17-07-13.282Z.log](https://github.com/user-attachments/files/16314969/home-assistant_midea_ac_2024-07-19T17-07-13.282Z.log)

**Comment by mill1000** [comment]
If you can, try installing this branch: https://github.com/mill1000/midea-ac-py/tree/issue/failing_connects

You'll have to manually install it, I don't think HACs can install from a specific branch

**Comment by marnem** [comment]
Hi,
with this version it works correctly

**Comment by mill1000** [comment]
Cool. Thanks for confirming. Could you provide a log with debugging again? Just want to see how your devices are responding now.

**Comment by marnem** [comment]
sure,
here the logs

[home-assistant_midea_ac_2024-07-19T19-03-11.949Z.log](https://github.com/user-attachments/files/16316159/home-assistant_midea_ac_2024-07-19T19-03-11.949Z.log)

**Comment by mill1000** [comment]
Thanks. Glad it's working for you, but your devices act pretty oddly. 

They don't respond to capability requests either.

**Comment by mill1000** [comment]
Latest release contains the fix you need.
