### ISSUE TITLE
2024.9.0 breaks functionality for Toshiba AC unit

### ISSUE THREAD

**Issue by bkoerbel** [mill1000/midea-ac-py#226]
Works as expected in 2024.8.1

Attached debug log of 2024.9.0 integration setup:
[home-assistant_midea_ac_2024-09-04T01-40-20.522Z.log](https://github.com/user-attachments/files/16859716/home-assistant_midea_ac_2024-09-04T01-40-20.522Z.log)
Seems like this might be the relevant error:
`AttributeError: 'MideaClimateACDevice' object has no attribute '_swing_modes'. Did you mean: 'swing_modes'?`

**Comment by CRCinAU** [comment]
I get the same error on another A/C unit:
```
AttributeError: 'MideaClimateACDevice' object has no attribute '_swing_modes'. Did you mean: 'swing_modes'?
2024-09-04 12:37:24.170 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/midea_ac/climate.py", line 62, in async_setup_entry
    MideaClimateACDevice(hass, coordinator, config_entry.options)
  File "/config/custom_components/midea_ac/climate.py", line 174, in __init__
    _LOGGER.debug("Supported swing modes: '%s'.", self._swing_modes)
                                                  ^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 323, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MideaClimateACDevice' object has no attribute '_swing_modes'. Did you mean: 'swing_modes'?
2024-09-04 12:37:36.570 WARNING (MainThread) [msmart.device.AC.device] Device is not capable of display control.
```

**Comment by alexmarsaudon** [comment]
Just chiming in to +1 this. Same errors as the two users above on a Midea (rebranded Danby). 
![image](https://github.com/user-attachments/assets/1b60b44f-c41e-4776-9762-486a0a4f4349)

**Comment by mill1000** [comment]
Should be fixed by 2024.9.1

**Comment by CRCinAU** [comment]
Can confirm. 2024.9.1 does seem to function again.

Thanks for the quick fix :)

**Comment by alexmarsaudon** [comment]
^Same, Thanks for the insanely quick turnaround on this!
