### ISSUE TITLE
Dependency failed to update - AC entities unable to setup after recent update, listed as unknown

### ISSUE THREAD

**Issue by dj21d** [mill1000/midea-ac-py#233]
Integration Version: 2024.9.1
HA Core Version:  2024.9.1
HA Supervisor Version: 2024.08.0

Device: Danby DAC145EB6WDB-6
Device Firmware: V1.0.8(150023092237)

Device is failing to initialize during Home Assistant Startup. Errors are as follows:
```
Error while setting up midea_ac platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/midea_ac/climate.py", line 62, in async_setup_entry
    MideaClimateACDevice(hass, coordinator, config_entry.options)
  File "/config/custom_components/midea_ac/climate.py", line 125, in __init__
    if self._device.supports_freeze_protection:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supports_freeze_protection'. Did you mean: 'supports_freeze_protection_mode'?
```
```
Error while setting up midea_ac platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/midea_ac/select.py", line 46, in async_setup_entry
    if (supported_rates := coordinator.device.supported_rate_selects) is not [AC.RateSelect.OFF]:
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supported_rate_selects'. Did you mean: 'supported_fan_speeds'?
```
```
Error while setting up midea_ac platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/midea_ac/switch.py", line 43, in async_setup_entry
    if coordinator.device.supports_breeze_away:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supports_breeze_away'
```

To confirm, this device/integration was working flawlessly before this update which I'm eternally grateful for! Thank you for all the work on this.

**Comment by mill1000** [comment]
Can enable debug logging and reload the integration? It looks like somehow the underlying msmart-ng library is out of date and not getting updates like it should.

**Comment by dj21d** [comment]
@mill1000 Sure thing, here is the full debug log when HA starts
`2024-09-07 17:50:07.018 INFO (MainThread) [custom_components.midea_ac] Starting midea-ac-py for device ID 151732605236630 (192.168.20.25:6444). Using msmart-ng version 2024.7.3.
2024-09-07 17:50:07.018 INFO (MainThread) [msmart.lan] Creating new connection to 192.168.20.25:6444.
2024-09-07 17:50:07.026 DEBUG (MainThread) [msmart.lan] Connected to 192.168.20.25:6444.
2024-09-07 17:50:07.026 INFO (MainThread) [msmart.lan] Authenticating with 192.168.20.25:6444.
2024-09-07 17:50:07.026 DEBUG (MainThread) [msmart.lan] Sending data to 192.168.20.25:6444: 8370004020000000ddeba78330f07bdecd1b7fdc4191cf11f104eacf46f8ff5ac6a0424c0e9fe6e5a35931c04701b99e54d3aa602e739d92a29288cd9b4858a2c2f009468cfe94ca
2024-09-07 17:50:07.076 DEBUG (MainThread) [msmart.lan] Received data from 192.168.20.25:6444: 837000402001ae41ca3ab1ba4708da36fa3d50b2c412ba35c4119cccfb0244b523dfc43395cea31d49ce1016304a5450eb9c9b23c72539515ec7112e8cb84ded488db14f616b809e
2024-09-07 17:50:07.078 INFO (MainThread) [msmart.lan] Authentication with 192.168.20.25:6444 successful. Expiration: 2024-09-08T09:50:07+00:00, Local key: 2adbf87a416555204bbc31e9c717a0dbcea893b3b03add1f6236f53c3988b633
2024-09-07 17:50:08.085 INFO (MainThread) [custom_components.midea_ac] Querying capabilities for device ID 151732605236630.
2024-09-07 17:50:08.087 DEBUG (MainThread) [msmart.base_device] Sending command to 192.168.20.25:6444: aa0fac00000000000003b5010001e5a6
2024-09-07 17:50:08.090 DEBUG (MainThread) [msmart.lan] Sending packet to 192.168.20.25:6444: 5a5a01115800200000000000090832150709181496350900008a00000000000000000000000000000542065231b95b9123b7f675b1de90ae915c618b02ed2747fad73f2ffa0db1d30be009ee2a000e1dd5ef6b3a793d473d
2024-09-07 17:50:08.091 DEBUG (MainThread) [msmart.lan] Sending data to 192.168.20.25:6444: 8370007e2066c05cbdd05a109f584cc3777a36886fcdc11eeeb9f35afdbb7ca21487af5683510f65834efa4765e88c2b67ed43150bf0c3e31f24921d62781587af9bc56de2288d2c4790fdd12193840fc76207de0a1f45ac987a4ac876d6a10155a58a58e9e1d5673259a6730321ab2f12a0c065f76eae8ee75645de88b45469f3a676c296f6
2024-09-07 17:50:08.187 DEBUG (MainThread) [msmart.lan] Received data from 192.168.20.25:6444: 8370008e2063599600e1cf63fe88fdb9a80643b2d5553319c9aa71e04bd88fab732b42f5589bf516f6771b7506a4729d7eab117df4ab086b1dc44bedcf2529b6c3dde3ba7d7ba5f57ae70c66ef56c3598d8ae00b4d1fe5b4b2e21e5a652ca6b3761f5ed2964d12e350164630241c1546c5f3e0712b4c2d9dd5a03e873ccd5ff5c0a26a63a09f4b677c895e65e294c5fd74d0347926c8
2024-09-07 17:50:08.191 DEBUG (MainThread) [msmart.lan] Received packet from 192.168.20.25:6444: 5a5a01116800208000000000a60832150709181496350900008a0000000000000000018000000000de6747186f9a23ffa1cc88c34a68d834b05ca0c7625de4b126b108797ae807fdfbb33d08c24361855751aa258b0e9a353759efec34a7c4dcf71d5830cd11530e
2024-09-07 17:50:08.192 DEBUG (MainThread) [msmart.lan] Received response from 192.168.20.25:6444: aa29ac00000000000303b507120201021402010015020102170201021a0201021002010524020101990d
2024-09-07 17:50:08.192 DEBUG (MainThread) [msmart.base_device] Response from 192.168.20.25:6444 in 0.110000 seconds.
2024-09-07 17:50:08.192 DEBUG (MainThread) [msmart.device.AC.command] Capabilities response payload: b507120201021402010015020102170201021a0201021002010524020101
2024-09-07 17:50:08.193 DEBUG (MainThread) [msmart.device.AC.command] Raw capabilities: {'eco_mode': False, 'eco_mode_2': True, 'heat_mode': False, 'cool_mode': True, 'dry_mode': True, 'auto_mode': True, 'swing_horizontal': False, 'swing_vertical': False, 'filter_notice': True, 'filter_clean': False, 'turbo_heat': False, 'turbo_cool': False, 'fan_silent': False, 'fan_low': True, 'fan_medium': True, 'fan_high': True, 'fan_auto': True, 'fan_custom': False, 'display_control': True}
2024-09-07 17:50:08.194 DEBUG (MainThread) [msmart.base_device] Sending command to 192.168.20.25:6444: aa21ac00000000000003418100ff03ff000200000000000000000000000003028bdb
2024-09-07 17:50:08.195 DEBUG (MainThread) [msmart.lan] Sending packet to 192.168.20.25:6444: 5a5a01116800200000000000130832150709181496350900008a000000000000000000000000000065cd8728fc6a5d31e6464235e81fa3b372946460bceafc6eae86e4200896522a2f2c998033e1118f4064e3bd2c45af98a45116a325500fc81c109aa67227b181
2024-09-07 17:50:08.196 DEBUG (MainThread) [msmart.lan] Sending data to 192.168.20.25:6444: 8370008e20660b44d070d0c126106efbe7d0b707e7c18ef308d3940d40310e247a31b6523ad59803761e734f7b59b731dea3623905671ca2b3d3361f030865eeb033b466bb27e42291950eb9be3c281b879d43da9521c4b10cbe3307332efb62525c923a3a58dc64fab836e87b076b42f4bba763fc6360a085cbf7bb233bc41fbab0ec747278591abefca24705ef318f97f35c3f389f
2024-09-07 17:50:08.297 DEBUG (MainThread) [msmart.lan] Received data from 192.168.20.25:6444: 8370008e206335439fa3dca3faa6f128ba97abd57668b93195c2514eb7518d2990065cb6fee15e7d1f632cbabd9b2fedefd3a81efdedd666a4c96b164e9abadab31d424b4004a0171a24b46ea11d7e8b16d54972b23ac313264a4461fb33fc07713428f29b9e028906b031875ddddbff7b139029153f4f3968755accbc2d49abcc4e0766bc7407ff5ec22698e92ab81b2454d5f02108
2024-09-07 17:50:08.297 DEBUG (MainThread) [msmart.lan] Received packet from 192.168.20.25:6444: 5a5a011168002080000000001a4832150709181496350900008a0000000000000000018000000000dca1f4bb737528a5754127252ab3c21a68b98df283f8c0f6a728e91c5c6475fd0686a5856d3f517d999a74b3c6db4a15c3afd63003692c7d2dfef044b6741ff3
2024-09-07 17:50:08.297 DEBUG (MainThread) [msmart.lan] Received response from 192.168.20.25:6444: aa22ac00000000000303c000a6500000003000000054ff2000000000000000008ba6a2
2024-09-07 17:50:08.297 DEBUG (MainThread) [msmart.base_device] Response from 192.168.20.25:6444 in 0.100000 seconds.
2024-09-07 17:50:08.297 DEBUG (MainThread) [msmart.device.AC.command] State response payload: c000a6500000003000000054ff2000000000000000008b
2024-09-07 17:50:08.297 DEBUG (MainThread) [custom_components.midea_ac.coordinator] Finished fetching midea_ac data in 0.103 seconds (success: True)
2024-09-07 17:50:08.300 INFO (MainThread) [custom_components.midea_ac.binary_sensor] Setting up binary sensor platform.
2024-09-07 17:50:08.301 INFO (MainThread) [custom_components.midea_ac.button] Setting up button platform.
2024-09-07 17:50:08.301 INFO (MainThread) [custom_components.midea_ac.climate] Setting up climate platform.
2024-09-07 17:50:08.301 ERROR (MainThread) [homeassistant.components.climate] Error while setting up midea_ac platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/midea_ac/climate.py", line 62, in async_setup_entry
MideaClimateACDevice(hass, coordinator, config_entry.options)
File "/config/custom_components/midea_ac/climate.py", line 125, in __init__
if self._device.supports_freeze_protection:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supports_freeze_protection'. Did you mean: 'supports_freeze_protection_mode'?
2024-09-07 17:50:08.306 INFO (MainThread) [custom_components.midea_ac.number] Setting up number platform.
2024-09-07 17:50:08.306 INFO (MainThread) [custom_components.midea_ac.select] Setting up select platform.
2024-09-07 17:50:08.306 ERROR (MainThread) [homeassistant.components.select] Error while setting up midea_ac platform for select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/midea_ac/select.py", line 46, in async_setup_entry
if (supported_rates := coordinator.device.supported_rate_selects) is not [AC.RateSelect.OFF]:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supported_rate_selects'. Did you mean: 'supported_fan_speeds'?
2024-09-07 17:50:08.313 INFO (MainThread) [custom_components.midea_ac.sensor] Setting up sensor platform.
2024-09-07 17:50:08.314 INFO (MainThread) [custom_components.midea_ac.switch] Setting up switch platform.
2024-09-07 17:50:08.314 ERROR (MainThread) [homeassistant.components.switch] Error while setting up midea_ac platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
await asyncio.shield(awaitable)
File "/config/custom_components/midea_ac/switch.py", line 43, in async_setup_entry
if coordinator.device.supports_breeze_away:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AirConditioner' object has no attribute 'supports_breeze_away'
2024-09-07 17:50:23.490 DEBUG (MainThread) [msmart.base_device] Sending command to 192.168.20.25:6444: aa21ac00000000000003418100ff03ff00020000000000000000000000000303d590
2024-09-07 17:50:23.491 DEBUG (MainThread) [msmart.lan] Sending packet to 192.168.20.25:6444: 5a5a01116800200000000000311732150709181496350900008a000000000000000000000000000065cd8728fc6a5d31e6464235e81fa3b3553c1270500a690b50db22f43e80f968dfc4835a9e1397466b9ae12661353e340f980c0ad458d84f7c5952410d2c2e91
2024-09-07 17:50:23.492 DEBUG (MainThread) [msmart.lan] Sending data to 192.168.20.25:6444: 8370008e20668d9fec5bea33da26ade2368ea85b0902d4547dd3846b3b4e6d2b9bbddd9791d93211fc61566b13cbda0d97bdad72df497d38056abbc86d27fbc79e9a1ddc1f96b6be8074f63943931ab063645dbf3296409ff08d58b73dea9c0f5c64a6265452b97c13f67425dcddd7282396ab9911463e8dd3a8702f030c04b975a456f2e2bf90e88156665ea030e8f59d060075ae17
2024-09-07 17:50:23.583 DEBUG (MainThread) [msmart.lan] Received data from 192.168.20.25:6444: 8370008e2063def2599d429b982e2447dd2e967e63b90ec9713a1c131e726f5bd6267ddfe522044b5121f07b9baf422e4f3c55e1f9f9d26b803a7a57a90546d6e82bb8749705c03673fa72ba038b8c28769d3abcc342ba74ad33fb1234063d1476cb4ff5f4505854f2302c27a67c0b662026027a6ce89ad9a17e9aa350bdb320c8b87039158ad1c992fa4b16ac5e2c106bffc4aebbca
2024-09-07 17:50:23.584 DEBUG (MainThread) [msmart.lan] Received packet from 192.168.20.25:6444: 5a5a01116800208000000000389732150709181496350900008a0000000000000000018000000000dca1f4bb737528a5754127252ab3c21a68b98df283f8c0f6a728e91c5c6475fd211e38b8e5e9b81f86bd00b3a4c8c7b2f245fdfde087df6926cd5c7d16cdf39f
2024-09-07 17:50:23.584 DEBUG (MainThread) [msmart.lan] Received response from 192.168.20.25:6444: aa22ac00000000000303c000a6500000003000000054ff200000000000000000d5629c
2024-09-07 17:50:23.584 DEBUG (MainThread) [msmart.base_device] Response from 192.168.20.25:6444 in 0.090000 seconds.
2024-09-07 17:50:23.584 DEBUG (MainThread) [msmart.device.AC.command] State response payload: c000a6500000003000000054ff200000000000000000d5
2024-09-07 17:50:23.585 DEBUG (MainThread) [msmart.base_device] Sending command to 192.168.20.25:6444: aa20ac00000000000003412101440000000000000000000000000000000004097d
2024-09-07 17:50:23.585 DEBUG (MainThread) [msmart.lan] Sending packet to 192.168.20.25:6444: 5a5a011168002000000000003a1732150709181496350900008a00000000000000000000000000004df41268bcc8851e137054298f7e818e9bfb057201a09210d5d29d5fbddb7f39d4f7a656c735cb8da90efb357fe358c66613c680e33afb9da2dbb208852fc21c
2024-09-07 17:50:23.585 DEBUG (MainThread) [msmart.lan] Sending data to 192.168.20.25:6444: 8370008e206627091eba91a98148f6e005e730d3d53092728f6896b965988c0dfd18fd72ea7078d6e3e48e360785caff3056160e692b551a61dfdaa8a85670a6e8f485302ad57d0ac8cd71b0e15ed892eae3ba2ba4605a7493e0dfcfa21c55a27ed3e3dddefc0e576922a82c4143525ac06bf6cc4277ebd6fe11529e41be2f1ffcd44fbd016a928276088c1446288823a4467908e47b
2024-09-07 17:50:23.697 DEBUG (MainThread) [msmart.lan] Received data from 192.168.20.25:6444: 8370008e2063a755022d4a1b154c04ff72830a28261759387c11bc04951788ece2530bd38a9e552c43787fb17fc147e22c7129e95a5e91207a5db72a26a8abca29df0037660a612a7fc4342ed6f4f032d10456e11bc8d1d7c8de29e3169f871d867db16c4f9548daa16b2686810622ebc89f649040b418790b25a191f49d3644bca7abfd35ec425735536d6558cf9ededc0a557daf90
2024-09-07 17:50:23.698 DEBUG (MainThread) [msmart.lan] Received packet from 192.168.20.25:6444: 5a5a01116800208000000000aa9732150709181496350900008a0000000000000000018000000000d26e95ddb450e51cac5db40332126e824bdfb3e16e33d88768cc4c3d0658937d0493fca1be3ea6041d59daa3c0eae8248a56e4dad2eb645c563c914c38b88bc8
2024-09-07 17:50:23.699 DEBUG (MainThread) [msmart.lan] Received response from 192.168.20.25:6444: aa22ac00000000000303c12101c40000000000000000000000000000000000007d0efa
2024-09-07 17:50:23.699 DEBUG (MainThread) [msmart.base_device] Response from 192.168.20.25:6444 in 0.110000 seconds.
2024-09-07 17:50:23.699 DEBUG (MainThread) [msmart.device.AC.command] Energy response payload: c12101c40000000000000000000000000000000000007d
2024-09-07 17:50:23.700 DEBUG (MainThread) [custom_components.midea_ac.coordinator] Finished fetching midea_ac data in 0.210 seconds (success: True)`

**Comment by mill1000** [comment]
> 2024-09-07 17:50:07.018 INFO (MainThread) [custom_components.midea_ac] Starting midea-ac-py for device ID 151732605236630 (192.168.20.25:6444). Using msmart-ng version 2024.7.3.


Yeah it's using an old version of the library. How are you installing the integration? Might be worth a reinstall to see if the dependency will right itself

**Comment by dj21d** [comment]
I've been installing this through HACS. Just removed it, restarted, re-added it, restarted, and setup the device. Same errors.

**Comment by mill1000** [comment]
Anything else in the home-assistant.log of interest? 

Can you check the manifest.json in custom_components/midea_ac/

**Comment by dj21d** [comment]
Nothing else in home assistant log, even when looking at the full log
Here is my manifest.json for the integration
```
{
  "domain": "midea_ac",
  "name": "Midea Smart AC",
  "codeowners": [
    "@mill1000"
  ],
  "config_flow": true,
  "dependencies": [],
  "documentation": "https://github.com/mill1000/midea-ac-py",
  "iot_class": "local_polling",
  "issue_tracker": "https://github.com/mill1000/midea-ac-py/issues",
  "loggers": [
    "msmart"
  ],
  "requirements": [
    "msmart-ng>=2024.9.0"
  ],
  "version": "2024.9.1"
}
```

**Comment by mill1000** [comment]
Odd. Nothing looks out of place. 

Try adding this to your configuration.yaml, restart HA and post the logs.

```
logger:
  default: debug
```

**Comment by dj21d** [comment]
Interesting. So I setup debug mode, I see this message
```
2024-09-08 18:58:26.329 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of msmart-ng>=2024.9.0
2024-09-08 18:58:26.329 DEBUG (SyncWorker_5) [homeassistant.util.package] Running pip command: args=['/usr/local/bin/python3', '-m', 'pip', 'install', '--quiet', 'msmart-ng>=2024.9.0', '--timeout', '60', '--upgrade', '--constraint', '/usr/src/homeassistant/homeassistant/package_constraints.txt']
```

But then nothing else until 
```
2024-09-08 19:13:35.638 INFO (MainThread) [custom_components.midea_ac] Starting midea-ac-py for device ID 151732605236630 (192.168.20.25:6444). Using msmart-ng version 2024.7.3.
```

The txt file it gives doesn't exist for me, so I'm trying to find where it actually is.

**Comment by mill1000** [comment]
Can you try running that command inside your HA container? (Assuming HAOS or Docker setup)

**Comment by dj21d** [comment]
Disk space is fine, just verified I'm only at 26% utilization on the VM.
What's even more strange is that when I access the host os and install/verify the package, it's correct.
```
homeassistant:/config# pip install msmart-ng>=2024.9.0 --timeout 60 --upgrade --constraint /usr/src/homeassistant/homeassistant/package_constraints.txt
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
homeassistant:/config# pip show msmart-ng
Name: msmart-ng
Version: 2024.9.0
Summary: A Python library for local control of Midea (and associated brands) smart air conditioners.
Home-page: 
Author: 
Author-email: Tucker Kern <tuckkern@gmail.com>
License: MIT
Location: /usr/local/lib/python3.12/site-packages
Requires: httpx, pycryptodome
Required-by: 
```
Verified after a HA restart that I get the same version being returned as well. Just for some reason I'm using an older version of the package in the integration startup

**Comment by mill1000** [comment]
Are you executing that inside the container that is running HA?

**Comment by dj21d** [comment]
Correct, I run this application on a VM with HA OS. To run that command I downloaded the Advanced SSH & Web Terminal AddOn, and ran `docker exec -it homeassistant bash` to access the container environment.

**Comment by mill1000** [comment]
Gotcha.

If it's still picking up version 2024.7.3 is must have installed that to some other location. 

What happens if you remove the integration and manually remove the msmart-ng packages(s)?

I'm pretty much grasping at straws here.

**Comment by dj21d** [comment]
Yeah I really don't get it either.

- Removed device, uninstalled the integration
- pip says 2024.9.0 is still installed
- Uninstalled the package via pip and confirmed the package was gone
- Restarted HA
- Re-added the integration from HACS, restarted
- Pip says package is not installed
- Added AC Unit, restarted, same errors. Logs say 2024.7.3 in use, pip says 2024.9.0 is installed.

At this point I might go post on the Home Assistant community forums because this doesn't sound like an integration issue. I appreciate all the help along the way though. The brightside is I haven't needed to turn on my AC since this problem started haha.

**Comment by mill1000** [comment]
That would probably be best at this point since it seems HA is installing/referencing the wrong requirement.

**Comment by Kosztyk** [comment]
Hi,

I have same issue with Midea Smart AC, same as you i uninstall it and the dependency but no luck with them, still not working.
The only solution found was to install integration version 2024.5.4, same version as msmart-ng and started to work, i even updated it after to last version and issue returned. 
 For the time being i am stuck with v2024.5.4.
Any other ideas to make it work will be appreciated.

Thank you

**Comment by mill1000** [comment]
@dj21d Did end up creating a thread on the HA community forum? I'm going to make a post unless you have already.

**Comment by dj21d** [comment]
@mill1000 Sorry I have not had a chance to create the thread yet. That would be amazing if you could.
@Kosztyk I downgraded to 2024.7.11 and that works for me, maybe yours is caching an even older version of the package?

**Comment by mill1000** [comment]
No problem. I'll handle it.

Yes, his is caching all the way back to 2024.5.4

**Comment by mill1000** [comment]
https://community.home-assistant.io/t/custom-integration-requirements-failing-to-update/772204

**Comment by mill1000** [comment]
This was resolved in the above community thread.

In summary, both users had older versions of `msmart-ng` in their `/config/deps` directory, The recommended resolution was to remove all the contents of `/config/deps` as it is generally deprecated.

@dj21d Left specific instructions on removing the directory via the SSH Add-on here:

https://community.home-assistant.io/t/custom-integration-requirements-failing-to-update/772204/23?u=mill1000
