### ISSUE TITLE
Midea AC intermittedly becomes unavailable.

### ISSUE THREAD

**Issue by Merril-r** [mill1000/midea-ac-py#254]
Goodday,

I have noticed that my midea ac becomes unavailable then available intermittedly. This is my first time installing the integration. This happens on two of my units.

Diagnostic log.
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Africa/Johannesburg",
    "os_name": "Linux",
    "os_version": "6.6.46-haos",
    "supervisor": "2024.10.0",
    "host_os": "Home Assistant OS 13.1",
    "docker_version": "26.1.4",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "midea_ac": {
      "documentation": "https://github.com/mill1000/midea-ac-py",
      "version": "2024.10.1",
      "requirements": [
        "msmart-ng>=2024.9.0"
      ]
    },
    "alexa_media": {
      "documentation": "https://github.com/alandtse/alexa_media_player/wiki",
      "version": "4.13.4",
      "requirements": [
        "alexapy==1.29.2",
        "packaging>=20.3",
        "wrapt>=1.14.0"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.1",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "midea_ac",
    "name": "Midea Smart AC",
    "codeowners": [
      "mill1000"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/mill1000/midea-ac-py",
    "iot_class": "local_polling",
    "issue_tracker": "https://github.com/mill1000/midea-ac-py/issues",
    "loggers": [
      "msmart"
    ],
    "requirements": [
      "msmart-ng>=2024.9.0"
    ],
    "version": "2024.10.1",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 1.549581065773964e-05
    },
    "01JA5CHM2YVWTFG4TPNDWRSNC9": {
      "wait_import_platforms": -0.0020050639286637306,
      "config_entry_setup": 1.9061271317768842
    }
  },
  "data": {
    "config_entry": {
      "created_at": "2024-10-14T11:27:49.342264+00:00",
      "data": {
        "id": 30786325851843,
        "host": "172.16.40.24",
        "port": 6444,
        "token": "**REDACTED**",
        "k1": "**REDACTED**"
      },
      "discovery_keys": {},
      "disabled_by": null,
      "domain": "midea_ac",
      "entry_id": "01JA5CHM2YVWTFG4TPNDWRSNC9",
      "minor_version": 2,
      "modified_at": "2024-10-14T11:27:49.342267+00:00",
      "options": {
        "prompt_tone": true,
        "temp_step": 1.0,
        "fan_speed_step": 1,
        "use_fan_only_workaround": false,
        "show_all_presets": false,
        "additional_operation_modes": null,
        "max_connection_lifetime": null,
        "use_alternate_energy_format": false
      },
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "midea_ac 30786325851843",
      "unique_id": "30786325851843",
      "version": 1
    },
    "device": {
      "ip": "172.16.40.24",
      "port": 6444,
      "id": 30786325851843,
      "online": true,
      "supported": true,
      "type": 172,
      "name": null,
      "sn": null,
      "key": "**REDACTED**",
      "token": "**REDACTED**",
      "supported_modes": [
        5,
        3,
        2,
        4,
        1
      ],
      "supported_swing_modes": [
        0,
        3,
        12,
        15
      ],
      "supported_fan_speeds": [
        20,
        40,
        60,
        80,
        102,
        100
      ],
      "supports_custom_fan_speed": true,
      "supported_rate_selects": [
        100
      ],
      "supports_eco": true,
      "supports_ieco": false,
      "supports_turbo": true,
      "supports_freeze_protection": true,
      "supports_display_control": false,
      "supports_filter_reminder": false,
      "supports_self_clean": true,
      "supports_purifier": true,
      "supports_humidity": false,
      "supports_target_humidity": false,
      "supports_vertical_swing_angle": true,
      "supports_horizontal_swing_angle": true,
      "supports_breezeless": false,
      "supports_breeze_mild": false,
      "supports_breeze_away": true,
      "enable_energy_usage_requests": true,
      "use_alternate_energy_format": false,
      "_supported_properties": [
        9,
        10,
        66,
        57
      ]
    }
  }
}
```

**Comment by mill1000** [comment]
Try setting the maximum connection lifetime.
https://github.com/mill1000/midea-ac-py?tab=readme-ov-file#resolving-connectivity-issues

**Comment by Merril-r** [comment]
> Try setting the maximum connection lifetime. https://github.com/mill1000/midea-ac-py?tab=readme-ov-file#resolving-connectivity-issues

I made the change you mentioned. Still getting the intermittent unavailable. Sometimes it stays unavailable then I have to restart the integration a couple of times.

This is in the HA log file:

This error originated from a custom integration.

Logger: msmart.base_device
Source: custom_components/midea_ac/coordinator.py:39
integration: Midea Smart AC (documentation, issues)
First occurred: 08:08:20 (155 occurrences)
Last logged: 08:56:21

Network timeout 172.16.40.24:6444: No response from host.
No response from 172.16.40.24:6444 in 6.000000 seconds.
No response from 172.16.40.24:6444 in 10.140000 seconds.
No response from 172.16.40.24:6444 in 6.010000 seconds.
Network error 172.16.40.24:6444: Unsupported packet: 3a6ad7c470391fea94b834a1a0325cc47c97eddde77f87a1405b883966e679fd77b651ea711fb167869f07cda31c33f035e9454b9dafbac4fe0e6c2f2c823a13

This error originated from a custom integration.

Logger: msmart.lan
Source: custom_components/midea_ac/coordinator.py:39
integration: Midea Smart AC (documentation, issues)
First occurred: 08:43:58 (1 occurrences)
Last logged: 08:43:58

Read cancelled. Disconnecting.

Logger: msmart.lan
Source: runner.py:189
First occurred: 08:27:31 (1 occurrences)
Last logged: 08:27:31

Connection to 172.16.40.24:6444 lost. Error: [Errno 104] Connection reset by peer

This error originated from a custom integration.

Logger: msmart.device.AC.device
Source: custom_components/midea_ac/__init__.py:71
integration: Midea Smart AC (documentation, issues)
First occurred: 08:08:20 (1 occurrences)
Last logged: 08:08:20

Failed to query capabilities from 172.16.40.24:6444.

I have also included a debug file that I recorded when the integration become unavaialble.

[home-assistant_midea_ac_freezing-2024-10-15T06-46-00.354Z.log](https://github.com/user-attachments/files/17374002/home-assistant_midea_ac_freezing-2024-10-15T06-46-00.354Z.log)

**Comment by mill1000** [comment]
Can you keep debugging enabled and restart HA? I can't quite follow what happened to your device but it appears to be rejecting the authentication process.

**Comment by Merril-r** [comment]
> Thanks. Some disconnects are occurring on a 60s interval. Try reducing your connection lifetime to 45 seconds.

I will try that and monitor. I will keep you posted

**Comment by mill1000** [comment]
How's it going? I'm assuming no news might be good news?

**Comment by mill1000** [comment]
Well if you can grab a debug log of a long session e.g. 1 hour+ I could take another look.

**Comment by mihaitaiosub** [comment]
I'm facing the same problem. I have three air conditioners that occasionally become unavailable for 30-50 seconds.

**Comment by mill1000** [comment]
Have you tried any of the recommended solutions? (I.e. max connection lifetime)

**Comment by mihaitaiosub** [comment]
Yes, I tried several times, namely 30, 45 and 60 seconds, without any result.

**Comment by mill1000** [comment]
Please provide debug logs if you want me to assist.

**Comment by mihaitaiosub** [comment]
Ok,I have attached the file requested.
[error_log.bin.zip](https://github.com/user-attachments/files/18400358/error_log.bin.zip)

**Comment by mihaitaiosub** [comment]
I have to tell you that the command you are talking about does not exist in the air conditioner presets, and anyway the air conditioners become unavailable even if I do not give them any commands. I am attaching a screenshot from last night showing this.
![Screenshot_20250116_041850_Home Assistant](https://github.com/user-attachments/assets/36970308-872c-4919-87cc-601a0bf98ad5)

**Comment by mill1000** [comment]
Hm...well something was causing those commands to be sent that we should get to the bottom of.

FYI, debug logs are far more useful then screenshots. :)

**Comment by mihaitaiosub** [comment]
I am attaching to this message another debugging file that captured the moment a device became unavailable.

[error_log.bin.zip](https://github.com/user-attachments/files/18486158/error_log.bin.zip)

**Comment by JBoye** [comment]
I am having the same issues, I hope this can be helpful

```
2025-01-28 13:56:06.068 DEBUG (MainThread) [custom_components.midea_ac.climate] Supported operational modes: '[<HVACMode.AUTO: 'auto'>, <HVACMode.COOL: 'cool'>, <HVACMode.DRY: 'dry'>, <HVACMode.HEAT: 'heat'>, <HVACMode.FAN_ONLY: 'fan_only'>, <HVACMode.OFF: 'off'>]'.
2025-01-28 13:56:06.069 DEBUG (MainThread) [custom_components.midea_ac.climate] Supported preset modes: '['none', 'sleep', 'away', 'eco', 'boost']'.
2025-01-28 13:56:06.069 DEBUG (MainThread) [custom_components.midea_ac.climate] Supported fan modes: '['auto', 'max', 'high', 'medium', 'low', 'silent']'.
2025-01-28 13:56:06.069 DEBUG (MainThread) [custom_components.midea_ac.climate] Supported swing modes: '['off', 'vertical', 'horizontal', 'both']'.
```

```
2025-01-28 13:57:08.075 ERROR (MainThread) [custom_components.midea_ac.coordinator] Unexpected error fetching midea_ac data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/queues.py", line 186, in get
    await getter
asyncio.exceptions.CancelledError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/msmart/lan.py", line 612, in send
    responses.append(await self._read())
                     ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/lan.py", line 555, in _read
    packet = await self._protocol.read(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/lan.py", line 128, in read
    return await self._read_queue(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/lan.py", line 122, in _read_queue
    return await asyncio.wait_for(self._queue.get(), timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/midea_ac/coordinator.py", line 39, in _async_update_data
    await self._device.refresh()
  File "/usr/local/lib/python3.13/site-packages/msmart/device/AC/device.py", line 481, in refresh
    for response in await self._send_command_get_responses(cmd):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/device/AC/device.py", line 370, in _send_command_get_responses
    responses = await super()._send_command(command)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/base_device.py", line 38, in _send_command
    responses = await self._lan.send(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/msmart/lan.py", line 617, in send
    self._protocol.peer)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'peer'
```


```
2025-01-28 13:57:08.075 ERROR (MainThread) [custom_components.midea_ac.coordinator] Unexpected error fetching midea_ac data
  File "/config/custom_components/midea_ac/coordinator.py", line 39, in _async_update_data
```

**Comment by JBoye** [comment]
I have connection lifetime set to 30s
![Image](https://github.com/user-attachments/assets/b04c45a3-2ba5-4e0c-800e-dbe370c7d162)

**Comment by l2jalbe** [comment]
Same problem for me: I've tested 30sec, 60 sec, 90 sec and 300sec but always same problem

**Comment by mill1000** [comment]
@JBoye @l2jalbe Please provide full debug logs if you would like me to look into this.

@mihaitaiosub I don't have a solution for you. Your devices seem to all stop responding at the same time so it might be a network connectivity issue.

**Comment by JBoye** [comment]
[Midea Log.txt](https://github.com/user-attachments/files/18575840/Midea.Log.txt)

**Comment by mill1000** [comment]
> I don't know what to say, but with the old Midea Smart Aircon integration, these problems didn't happen.

The old integration logged any network issues at the debug level.
https://github.com/mac-zhou/midea-msmart/blob/97723d055d8e5a3775eaaca96807f2dbbd6db2aa/msmart/lan.py#L78-L96

I prefer to properly indicate errors instead of sweeping it under the rug, but you're more then welcome to switch back if that's a viable solution to you.


Your logs still show something attempting to send the unsupported iECO property, possibly by an automation or script.

If you want to continue debugging, limiting the test to a single device without any scripts or automation would make understanding the logs simpler and might isolate the issue.

**Comment by mill1000** [comment]
@JBoye In your log it appears that the connection lifetime is not set. Can you send me a log where it is set to 30 seconds?


The exceptions are something I'm looking into. I can't wrap my head around how those are getting thrown

**Comment by mill1000** [comment]
Adding this to your configuration would suppress most logs except the ones of interest
```yaml
logger:
  default: critical
  logs:
    custom_components.midea_ac: info
    msmart: debug
```

**Comment by mill1000** [comment]
@JBoye Upon further review it appears that your device doesn't respond to requests for humidity information. This might be causing some of the problem. Can you enable debug logging and restart HA or reload the integration?

**Comment by JBoye** [comment]
More logs with debug enabled and connection lifetime set to 30 seconds

[log 3.txt](https://github.com/user-attachments/files/18578887/log.3.txt)

**Comment by mill1000** [comment]
@JBoye Thanks. I believe your issue is that you've enabled the energy sensors but your device doesn't support them. Since the device doesn't respond, it's marked as offline.

For now, you should disable the energy sensors.

I've created an issue here about this https://github.com/mill1000/midea-msmart/issues/186,

**Comment by JBoye** [comment]
How do I disable them? 

![image](https://github.com/user-attachments/assets/3fba601f-ff41-488f-b161-3c74869780e9)

**Comment by mill1000** [comment]
From the device page, click the energy and power entities, click the gear icon, then toggle enabled to off.

Be sure to disable the current energy, total energy and power sensors.

![Image](https://github.com/user-attachments/assets/5c5b4b8e-c2b9-4ca3-8138-7e48291a1f7e)

![Image](https://github.com/user-attachments/assets/e998fdec-ee06-4420-92bf-48efaed509ba)

**Comment by mill1000** [comment]
> I disabled these sensors a long time ago. The problem still remained.

I never asked you to.

**Comment by JBoye** [comment]
> From the device page, click the energy and power entities, click the gear icon, then toggle enabled to off.
> 
> Be sure to disable the current energy, total energy and power sensors.
> 
> ![Image](https://github.com/user-attachments/assets/5c5b4b8e-c2b9-4ca3-8138-7e48291a1f7e)
> 
> ![Image](https://github.com/user-attachments/assets/e998fdec-ee06-4420-92bf-48efaed509ba)

Thanks, that worked for me

**Comment by mill1000** [comment]
I'm closing this issue as I believe the OPs issue is more-or-less resolved.
